swagger: "2.0"
info:
  description: "VPC Flow Log Graph Diff API."
  version: "1.0.0"
  title: "VPC Differ"
basePath: "/"
schemes:
  - "https"
produces:
  - "application/octet-stream"
paths:
  /:
    post:
      summary: "Generate a diff."
      parameters:
        - name: "previous_start"
          in: "query"
          description: "The start time of the previous graph."
          required: true
          type: "string"
          format: "date-time"
        - name: "previous_stop"
          in: "query"
          description: "The stop time of the previous graph."
          required: true
          type: "string"
          format: "date-time"
        - name: "next_start"
          in: "query"
          description: "The start time of the next graph."
          required: true
          type: "string"
          format: "date-time"
        - name: "next_stop"
          in: "query"
          description: "The stop time of the next graph."
          required: true
          type: "string"
          format: "date-time"
      responses:
        409:
          description: "The diff for this range already exists."
        202:
          description: "The diff will be created."
    get:
      summary: "Fetch a complete diff."
      parameters:
        - name: "previous_start"
          in: "query"
          description: "The start time of the previous graph."
          required: true
          type: "string"
          format: "date-time"
        - name: "previous_stop"
          in: "query"
          description: "The stop time of the previous graph."
          required: true
          type: "string"
          format: "date-time"
        - name: "next_start"
          in: "query"
          description: "The start time of the next graph."
          required: true
          type: "string"
          format: "date-time"
        - name: "next_stop"
          in: "query"
          description: "The stop time of the next graph."
          required: true
          type: "string"
          format: "date-time"
      responses:
        404:
          description: "The diff for this range does not exist yet."
        204:
          description: "The diff is created but not yet complete."
        200:
          description: "Success."