// Automatically generated by MockGen. DO NOT EDIT!
// Source: ./pkg/domain/differ.go

package v1

import (
	"bitbucket.org/atlassian/vpcflow-diffd/pkg/domain"
	context "context"
	gomock "github.com/golang/mock/gomock"
	io "io"
)

// Mock of Differ interface
type MockDiffer struct {
	ctrl     *gomock.Controller
	recorder *_MockDifferRecorder
}

// Recorder for MockDiffer (not exported)
type _MockDifferRecorder struct {
	mock *MockDiffer
}

func NewMockDiffer(ctrl *gomock.Controller) *MockDiffer {
	mock := &MockDiffer{ctrl: ctrl}
	mock.recorder = &_MockDifferRecorder{mock}
	return mock
}

func (_m *MockDiffer) EXPECT() *_MockDifferRecorder {
	return _m.recorder
}

func (_m *MockDiffer) Diff(ctx context.Context, d domain.Diff) (io.ReadCloser, error) {
	ret := _m.ctrl.Call(_m, "Diff", ctx, d)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockDifferRecorder) Diff(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Diff", arg0, arg1)
}
